# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'

variables:

  #API_VERSION: "apigeeapi" 
  # or 
  API_VERSION: "googleapi"

  DEFAULT_APIGEE_ENV: "default-dev"
  DEFAULT_APIGEE_ORG: "bap-emea-apigee-5"
 
  TEST_HOST: bap-emea-apigee-5-dev.lalevee.org
  #TEST_HOST: "$(APIGEE_ORG)-$(APIGEE_ENV).apigee.net"
  #34.117.38.184.nip.io

  AUTHOR_EMAIL: $(APIGEE_USER)
  COMMIT_ID: $(Build.SourceVersion)
  COMMIT_BRANCH: $(Build.SourceBranch)

  # GCP_SERVICE_ACCCOUNT, APIGEE_USER & APIGEE_PASSWORD are stored in Azure Pipeline variable settings
  

steps:


# Main branch for Apigee test environment
- bash: |
    if [ $COMMIT_BRANCH == "main" ]; then
      # Prod branch --> Apigee prod environment 
      echo "##vso[task.setvariable variable=APIGEE_ORG]$DEFAULT_APIGEE_ORG"
      echo "##vso[task.setvariable variable=APIGEE_ENV]prod"

    else
      # all ohers branches --> defualt environment
      echo "##vso[task.setvariable variable=APIGEE_ORG]$DEFAULT_APIGEE_ORG"
      echo "##vso[task.setvariable variable=APIGEE_ENV]$DEFAULT_APIGEE_ENV"
    fi
  enabled: "true"
  displayName: Set Deployment Target
  env:  
    DEFAULT_APIGEE_ORG: $(c_APIGEE_ORG)
    DEFAULT_APIGEE_ENV: $(DEFAULT_APIGEE_ENV)


# install node.js tools and dependencies
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  enabled: "false"
    
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.'
  displayName: npmInstalls
  enabled: "false"


# run Apigeelint, API proxy linter
# generate result output in Junit because Azure task PublishTestResults doesn't (yet) support html
- bash: |
    echo "run Apigeelint" 
    mkdir test_output
    ./node_modules/apigeelint/cli.js -s apiproxy/ -e PO013 -f html.js  > test_output/apigeelint-output.html
    cat test_output/apigeelint-output.html
  enabled: "false"
  displayName: runApigeeLint


# run ESlint, javascript linter
- bash: |
    echo "run Eslint"
    ./node_modules/eslint/bin/eslint.js -c ./.eslintrc-jsc.yml --format html ./apiproxy/resources/jsc > test_output/eslint-out.html
    cat test_output/eslint-out.html
  enabled: "false"
  displayName: runESlint


# Publish static code analysis folder result
- task: PublishBuildArtifacts@1
  displayName: publishStaticCodeTestsResults
  enabled: "false"
  inputs:
    pathToPublish: test_output
    artifactName: static-code-analysis


# Configure EdgeeConfig/edge.json file: update target environment name
- bash: |
    sed -i "s/target_apigee_env/$(APIGEE_ENV)/g" ./EdgeConfig/edge.json
  enabled: "false"
  displayName: Update edge.json

# Generate GCP Service Account file from Azure Pipeline variable GCP_SERVICE_ACCCOUNT
# if deploy to Apigee X/hybrid
- bash: |
    echo '$(GCP_SERVICE_ACCCOUNT)' > sa.json
  enabled: "false"
  condition:  eq(variables.API_VERSION, 'googleapi')
  displayName: Generate SA Key file 
  env:  
    GCP_SERVICE_ACCCOUNT: $(GCP_SERVICE_ACCCOUNT)



# Maven Deploy Apigee Configuration (from EdgeeConfig/edge.json): Apigee edge
- task: Maven@3
  displayName: mvnApigeeConfigurationApigee
  enabled: "false"
  condition:  eq(variables.API_VERSION, 'apigeeapi')
  inputs:
    mavenPomFile: './pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: "install -P$(API_VERSION) -Dapigee.org=$(APIGEE_ORG) -Denv=$(APIGEE_ENV) -Dapigee.username=$(APIGEE_CREDS_USR) -Dapigee.password=$(APIGEE_CREDS_PSW) -Dapigee.config.file=EdgeConfig/edge.json -Dapigee.config.options=update"
  env:  
      APIGEE_PASS: $(APIGEE_PASS)
        
# Maven Deploy Apigee Configuration (from EdgeeConfig/edge.json): Apigee X/hybrid
- task: Maven@3
  displayName: mvnApigeeConfigurationGoogle
  enabled: "false"
  condition:  eq(variables.API_VERSION, 'googleapi')
  inputs:
    mavenPomFile: './pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: "install -P$(API_VERSION) -Dapigee.org=$(APIGEE_ORG) -Denv=$(APIGEE_ENV) -Dsa=sa.json -Dapigee.config.file=./EdgeConfig/edge.json -Dapigee.config.options=update"

# Maven Config Env.
- task: Maven@3
  displayName: mvnProcessResources
  enabled: "false"
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: "process-resources -P$(API_VERSION) -Dcommit=$(GIT_COMMIT) -Dbranch=$(GIT_BRANCH) -Dauthor=$(AUTHOR_EMAIL) -e"


# Maven Package proxy bundle
- task: Maven@3
  displayName: mvnApigeeConfigure
  enabled: "false"
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: "apigee-enterprise:configure -P$(API_VERSION) -Dorg=$(APIGEE_ORG) -Denv=$(APIGEE_ENV)" 


# Maven Deploy proxy bundle: Apigee Edge
- task: Maven@3
  displayName: mvnApigeeDeployApigee
  enabled: "false"
  condition:  eq(variables.API_VERSION, 'apigeeapi')
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: "apigee-enterprise:deploy -P$(API_VERSION) -Dorg=$(APIGEE_ORG) -Denv=$(APIGEE_ENV) -Dpassword=$(APIGEE_CREDS_PSW) -Dusername=$(APIGEE_CREDS_USR)" 
  env:
    APIGEE_PASS: $(APIGEE_PASS)

# Maven Deploy proxy bundle: Apigee X/hybrid
- task: Maven@3
  displayName: mvnApigeeDeployGoogle
  enabled: "false"
  condition:  eq(variables.API_VERSION, 'googleapi')
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: "apigee-enterprise:deploy -P$(API_VERSION) -Dapigee.org=$(APIGEE_ORG) -Denv=$(APIGEE_ENV) -Dsa=sa.json" 
    

# run Apickli, API test integration
- bash: |
    echo "run Apickli"
    mkdir integration_output
    export NODE_TLS_REJECT_UNAUTHORIZED="0"
    sed -i "s/organization_hostname/$TEST_HOST/g" ./test/integration/features/support/init.js
    node ./node_modules/cucumber/bin/cucumber-js ./test/integration --format json:report.json
    node ./test/integration/index.js
    cp ./cucumber_report.html integration_output/apickli_report.html 
  displayName: runApickli
  enabled: "false"


# Publish integration test folder result
- task: PublishBuildArtifacts@1
  displayName: publishInteegrationTestsResults
  enabled: "false"
  inputs:
    pathToPublish: integration_output
    artifactName: integration-tests


