# Maven

# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master
- releases/*

pool:
  vmImage: 'ubuntu-latest'

variables:

  #API_VERSION: "googleapi" 
  # or 
  API_VERSION: "googleapi"

  APIGEE_USER_ENV: $(APIGEE_USER)
  APIGEE_ENV: "default-dev"
  APIGEE_ORG: "bap-emea-apigee-5"

  AUTHOR_EMAIL: $(APIGEE_USER)
  COMMIT_ID: $(Build.SourceVersion)
  COMMIT_BRANCH: $(Build.SourceBranch)

  #TEST_HOST: "$(APIGEE_ORG)-$(APIGEE_ENV).apigee.net"
  TEST_HOST: bap-emea-apigee-5-dev.lalevee.org

  # GCP_SERVICE_ACCCOUNT, APIGEE_CREDS_USR & APIGEE_CREDS_PSW are stored in Azure Pipeline variable settings
  

steps:
    
# install node.js tools and dependencies
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
  enabled: "true"
    
- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '.'
  displayName: npmInstalls
  enabled: "true"


# run Apigeelint, API proxy linter
# generate result output in Junit because Azure task PublishTestResults doesn't (yet) support html
- bash: |
    echo "run Apigeelint" 
    mkdir test_output
    ./node_modules/apigeelint/cli.js -s apiproxy/ -e PO013 -f junit.js > test_output/apigeelint-output.xml
    cat apigeelint-output.xml
  enabled: "true"
  displayName: runApigeeLint

- task: PublishTestResults@2
  displayName: publishApigeelintResults
  enabled: "true"
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*-output.xml'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: test_output
    artifactName: apigeelint

# run ESlint, javascript linter
- bash: |
    echo "run Eslint"
    ./node_modules/eslint/bin/eslint.js -c .eslintrc-jsc.yml --format junit apiproxy/resources/jsc > eslint-out.xml
    cat eslint-out.xml
  enabled: "true"
  displayName: runESlint

- task: PublishTestResults@2
  displayName: publishESlintResults
  enabled: "true"
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*-output.xml'


# Configure EdgeeConfig/edge.json file: update target environment name
- bash: |
    sed -i "s/target_apigee_env/$(APIGEE_ENV)/g" ./EdgeConfig/edge.json
  enabled: "false"
  displayName: Update edge.json

# Generate GCP Service Account file from Azure Pipeline variable GCP_SERVICE_ACCCOUNT
# if deploy to Apigee X/hybrid
- bash: |
    echo '$(GCP_SERVICE_ACCCOUNT)' > sa.json
  enabled: "false"
  condition:  eq(variables.API_VERSION, 'googleapi')
  displayName: Generate SA Key file 
  env:  
    GCP_SERVICE_ACCCOUNT: $(GCP_SERVICE_ACCCOUNT)


# Maven Deploy Apigee Configuration (from EdgeeConfig/edge.json): Apigee edge
- task: Maven@3
  displayName: mvnApigeeConfigurationApigee
  enabled: "false"
  condition:  eq(variables.API_VERSION, 'apigeeapi')
  inputs:
    mavenPomFile: './pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: "install -P$(API_VERSION) -Dapigee.org=$(APIGEE_ORG) -Denv=$(APIGEE_ENV) -Dapigee.username=$(APIGEE_CREDS_USR) -Dapigee.password=$(APIGEE_CREDS_PSW) -Dapigee.config.file=EdgeConfig/edge.json -Dapigee.config.options=update"
  env:  
      APIGEE_PASS: $(APIGEE_PASS)
        
# Maven Deploy Apigee Configuration (from EdgeeConfig/edge.json): Apigee X/hybrid
- task: Maven@3
  displayName: mvnApigeeConfigurationGoogle
  enabled: "false"
  condition:  eq(variables.API_VERSION, 'googleapi')
  inputs:
    mavenPomFile: './pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: "install -P$(API_VERSION) -Dapigee.org=$(APIGEE_ORG) -Denv=$(APIGEE_ENV) -Dsa=sa.json -Dapigee.config.file=./EdgeConfig/edge.json -Dapigee.config.options=update"

# Maven Config Env.
- task: Maven@3
  displayName: mvnProcessResources
  enabled: "false"
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: "process-resources -P$(API_VERSION) -Dcommit=$(GIT_COMMIT) -Dbranch=$(GIT_BRANCH) -Dauthor=$(AUTHOR_EMAIL) -e"


# Maven Package proxy bundle
- task: Maven@3
  displayName: mvnApigeeConfigure
  enabled: "false"
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: "apigee-enterprise:configure -P$(API_VERSION) -Dorg=$(APIGEE_ORG) -Denv=$(APIGEE_ENV)" 


# Maven Deploy proxy bundle: Apigee Edge
- task: Maven@3
  displayName: mvnApigeeDeployApigee
  enabled: "false"
  condition:  eq(variables.API_VERSION, 'apigeeapi')
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: "apigee-enterprise:deploy -P$(API_VERSION) -Dorg=$(APIGEE_ORG) -Denv=$(APIGEE_ENV) -Dpassword=$(APIGEE_CREDS_PSW) -Dusername=$(APIGEE_CREDS_USR)" 
  env:
    APIGEE_PASS: $(APIGEE_PASS)

# Maven Deploy proxy bundle: Apigee X/hybrid
- task: Maven@3
  displayName: mvnApigeeDeployGoogle
  enabled: "false"
  condition:  eq(variables.API_VERSION, 'googleapi')
  inputs:
    mavenPomFile: 'pom.xml'
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    goals: "apigee-enterprise:deploy -P$(API_VERSION) -Dapigee.org=$(APIGEE_ORG) -Denv=$(APIGEE_ENV) -Dsa=sa.json" 
    
# run Apickli, API test integration
# generate result output in Junit because Azure task PublishTestResults doesn't (yet) support html
- bash: |
    echo "run Apickli"
    echo "----------------------------"
    cd test/integration 
    npm install 
    sed -i "s/organization_hostname/$(TEST_HOST)/g" ./features/support/init.js
    cat ./features/support/init.js
    npm test
    echo "----------------------------"
    cat report.json | node_modules/cucumber-junit/bin/cucumber-junit  > apickli-output.xml 
  displayName: runApickli
  enabled: "false"

  # publish Apigeelint JUnit result
- task: PublishTestResults@2
  displayName: publishApickliResults
  enabled: "false"
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/*-output.xml'